-- Backfill blog_posts.conteudo + album from legacy JSON content files
-- Generated: 2026-05-01T19:39:34.482Z

UPDATE blog_posts SET conteudo = '<h2 class=''title''>Um cenário digno da realeza 👑</h2>
<p class=''description''>Neste Dia das Mães, preparamos um ambiente especial para eternizar o amor mais nobre que existe: o amor de mãe.</p>
<p class=''description''>Criamos um cenário delicado e encantador com tons pastel suaves, um sofá redondo acolhedor e um lindo arco floral em aramado, elementos que juntos celebram a beleza, a força e a doçura das nossas rainhas da vida real.</p>
<p class=''description''>Cada detalhe foi pensado para que nossas mães se sintam como merecem: honradas, admiradas e celebradas.</p>
<p class=''description''>Uma oportunidade única de registrar esse amor com leveza, elegância e muito carinho.</p>
<p class=''description''>Reserve seu ensaio e eternize esse momento com quem sempre esteve ao seu lado, desde o primeiro instante. 💖</p>', album = '[{"imageId":"b25c4856-522b-4367-2aac-6f1c36111100","width":850,"height":567,"format":"paisagem","customClass":"w50","alt":""},{"imageId":"49636a87-a093-4577-4b61-4b1bed232500","width":850,"height":567,"format":"paisagem","customClass":"w50","alt":""},{"imageId":"6ea326b0-e9e1-4b05-29c1-46146f52a400","width":850,"height":567,"format":"paisagem","customClass":"w50","alt":""},{"imageId":"c46a3468-a2dd-4446-5caa-ac555c7dd400","width":850,"height":567,"format":"paisagem","customClass":"w50","alt":""},{"imageId":"f15c8181-5d19-48f1-0525-8142dda65500","width":468,"height":703,"format":"retrato","customClass":"w33","alt":""},{"imageId":"1754195e-e114-473f-941f-bfd589ab7a00","width":468,"height":703,"format":"retrato","customClass":"w33","alt":""},{"imageId":"4552c7b3-0e6e-4371-6658-f36e0d8c5000","width":468,"height":703,"format":"retrato","customClass":"w33","alt":""}]' WHERE slug = 'nosso-cenario-do-dia-das-maes-2025';
UPDATE blog_posts SET conteudo = '<p class=''description''>Este ano, nossa intenção era fazer algo que fugisse do clichê. Pensamos em aliar a estética boho já presente no estúdio e nos afastar um pouco do padrão verde e vermelho.</p>
<p class=''description''>Nosso estúdio tem um cantinho cuja cor predominante é o dourado e tons terrosos. Achamos por bem investir nessas cores. Nesse caso, mantivemos o verde e dourado como as cores do nosso Natal 2024, com umas pitadinhas de prateado, aliando acessórios que já tínhamos no nosso ambiente.</p>
<p class=''description''>Conseguimos um resultado incrível com essa estética. É muito prazeroso para nós marcar a vida de vocês com nossas ideias de decoração. Ficamos muito contentes em fazer parte de suas vidas em forma de memórias e, quando se trata de família, o trabalho ganha ainda mais afetividade. Muito obrigado a todos e um ótimo Natal 2024!</p>', album = '[{"imageId":"ccfd5937-1c12-49e8-29b5-495a57f2e100","width":468,"height":703,"format":"retrato","customClass":"w33","alt":""},{"imageId":"2a2fd3a7-3738-4e74-fb36-597891dc1400","width":468,"height":703,"format":"retrato","customClass":"w33","alt":""},{"imageId":"773e07c8-28e1-4f08-ecac-5349b6561400","width":468,"height":703,"format":"retrato","customClass":"w33","alt":""},{"imageId":"dcebbd91-190e-40d1-6854-81795b3e2a00","width":850,"height":567,"format":"paisagem","customClass":"w50","alt":""},{"imageId":"0c157f6a-45ac-4bb2-e971-8b050016e300","width":850,"height":567,"format":"paisagem","customClass":"w50","alt":""},{"imageId":"6134aee5-471d-465e-071c-cb477c03d900","width":850,"height":567,"format":"paisagem","customClass":"w50","alt":""},{"imageId":"7468269a-7b97-4c75-867f-afd0171e9b00","width":850,"height":567,"format":"paisagem","customClass":"w50","alt":""},{"imageId":"76cc36dd-972b-4dd3-2b97-49af4a1d0a00","width":850,"height":567,"format":"paisagem","customClass":"w50","alt":""},{"imageId":"7fa7818b-eca5-4131-949e-842a5f0cc700","width":850,"height":567,"format":"paisagem","customClass":"w50","alt":""}]' WHERE slug = 'nosso-cenario-do-natal-2024';
UPDATE blog_posts SET conteudo = '<p class=''description''>Assim como em <b>2024</b>, colocamos muito carinho em cada detalhe para criar um cenário especial, algo que fugisse do convencional, mas que mantivesse aquela sensação de <b>aconchego, amor e magia</b> que o Natal sempre traz.</p>
<p class=''description''>No ano passado, o tema foi o <b>estilo Boho</b>, com <b>tons dourados e terrosos</b>, lembrando o clima acolhedor dos Natais da América do Norte, quase como aquelas paisagens com folhas secas e luzes suaves.</p>
<p class=''description''>Dessa vez, para <b>2025</b>, escolhemos uma nova paleta: <b>azul, dourado e branco</b>. 💙✨</p>
<p class=''description''>E, sinceramente, acredito que <b>nos superamos</b>!</p>
<p class=''description''>As cores têm significados diferentes dependendo de onde estamos (vide o filme Divertidamente, rs), mas aqui no Brasil, o <b>azul transmite tranquilidade, confiança, serenidade e harmonia</b>, exatamente o que queremos que você sinta ao ver esse cenário.</p>
<p class=''description''>Enquanto você confere as fotos aqui ao lado, espero que consiga sentir essa <b>atmosfera especial</b> que criamos com tanto cuidado. Cada detalhe foi pensado para que o seu ensaio em família seja <b>leve, cheio de afeto</b> e se transforme em <b>memórias lindas</b> deste Natal.</p>
<p class=''description''>E é com esse cenário que damos início à nossa <b>campanha de Natal 2025!</b> 🌟</p>
<p class=''description''>Todo ano, esse é um dos <b>momentos mais esperados</b> aqui no estúdio, ver as famílias voltando, as crianças crescendo e aquele <b>clima gostoso de final de ano</b> tomando conta de tudo.</p>
<p class=''description''>Esse ano, queremos que cada sessão seja <b>ainda mais especial</b>. As <b>fotos de Natal</b> não são só registros, são <b>lembranças que ganham vida</b> quando a gente olha de novo, anos depois. Por isso, preparamos <b>pacotes acessíveis, horários flexíveis</b> e todo o carinho de sempre pra te receber.</p>
<p class=''description''>💫 <b>Vem viver esse momento com a gente</b></p>
<p class=''description''>Se você já participou dos <b>ensaios anteriores</b>, vai se encantar com o <b>novo cenário</b>.<br>E se for o seu <b>primeiro Natal</b> com a gente, pode ter certeza de que será <b>inesquecível</b>.</p>
<p class=''description''>Logo abaixo, você confere o <b>banner oficial da campanha</b> com todas as informações de valores</b> e como <b>agendar seu ensaio</b>.</p>
<p class=''description''>A gente mal pode esperar pra <b>registrar esse Natal</b> com você e sua família! 📅📸</p>' WHERE slug = 'nosso-cenario-do-natal-2025';
UPDATE blog_posts SET conteudo = '<p class=''description''>Já reparou como alguns clichês sempre aparecem quando falamos de lições de vida?</p>
<quote>“A primeira impressão é a que fica.”</quote>
<p class=''description''>Por mais clichê que pareça, essa frase não está errada.</p>
<p class=''description''>As pessoas que nos veem, bem ou mal, fazem microjulgamentos em questão de segundos.</p>
<p class=''description''>“<i>Ah, mas isso é errado!</i>”… depende muito do contexto.</p>
<p class=''description''>Na minha rebeldia adolescente, eu também pensava assim. Mas, ao ler <b>O Pequeno Príncipe</b>, aprendi que também sou responsável pelo que cativo.</p>
<p class=''description''>E, especialmente no meio corporativo, isso faz toda diferença. O profissional precisa, sim, se portar com a autoridade e o respeito que o cargo exige. Mas isso não significa entrar numa “caixinha” estética antiga. É totalmente possível transmitir profissionalismo sem perder sua personalidade.</p>
<p class=''description''><b>E lembre-se:</b> ninguém deve gostar mais de você do que você mesmo. Então se vista bem, cuide-se, não só pelos outros, mas principalmente por você.</p>
<h2>Seu LinkedIn é sua vitrine profissional</h2>
<p class=''description''>Hoje, o seu LinkedIn é uma verdadeira vitrine da sua imagem profissional.</p>
<p class=''description''>Agora pensa comigo:</p>
<p class=''description''>um recrutador ou cliente acessa seu perfil…</p>
<p class=''description''>E encontra:</p>
<ul><li>uma foto com iluminação ruim</li><li>um fundo desorganizado</li><li>uma postura que não transmite confiança</li></ul>
<p class=''description''>Mesmo que você esteja bem vestido, a mensagem transmitida naquele primeiro segundo pode não ser boa.</p>
<p class=''description''>E às vezes, é nesse instante que uma oportunidade passa.</p>
<p class=''description''>Mas sabe o que vem depois da primeira oportunidade?</p>
<p class=''description''>A segunda. 🙂</p>
<p class=''description''><b>E é aqui que eu posso te ajudar</b></p>
<p class=''description''>Se você quer uma imagem mais profissional e alinhada com o mercado, eu posso te ajudar com isso na prática.</p>
<p class=''description''>Na página abaixo, você vai encontrar exemplos reais de ensaios corporativos, entender como funciona o processo e escolher o pacote ideal pra você.</p>
<p class=''description''>Tudo pensado para que você tenha fotos que transmitam profissionalismo, confiança e personalidade, sem complicação.</p>
<p class=''description''>E quanto à iluminação, cenário e direção?</p>
<p class=''description''>Bom… isso você pode deixar comigo. 😉</p>
<a href="/ensaio-profissional-em-mogi" class=''link-interno''>Veja como funciona o ensaio profissional em Mogi das Cruzes</a>' WHERE slug = 'quao-importante-e-fazer-um-ensaio-profissional-para-o-linkedin';
UPDATE blog_posts SET conteudo = '<p class=''description''>Se você é médico, advogado, psicólogo ou outro profissional em Mogi das Cruzes e região, investir em um ensaio fotográfico corporativo pode elevar sua imagem, atrair mais clientes e transmitir profissionalismo desde o primeiro contato. Neste post, explicamos as principais vantagens das fotos profissionais para perfis nas redes sociais, sites, cartões de visita e materiais de divulgação.</p>
<div class=''rows''><div><h2 class=''subtitle''>1. Primeira impressão forte e positiva</h2> <p class=''description''> A imagem é o primeiro contato que muitas pessoas terão com você ou seu negócio. Uma foto profissional transmite confiança, cuidado e credibilidade, seja no LinkedIn, no seu site ou em um cartão de visita. </p></div><div><h2 class=''subtitle''>2. Credibilidade e autoridade</h2> <p class=''description''> Fotos com boa iluminação, enquadramento e qualidade mostram que você leva seu trabalho a sério. Isso impacta diretamente a forma como os clientes enxergam seu profissionalismo. </p></div><div><h2 class=''subtitle''>3. Destaque em meio à concorrência</h2> <p class=''description''> Em um mundo visual, fotos amadoras se perdem no meio da multidão. Uma imagem profissional se destaca no feed das redes sociais e nos materiais impressos, gerando mais cliques, curtidas e atenção. </p></div><div><h2 class=''subtitle''>4. Identidade visual alinhada</h2> <p class=''description''> Fotografias com estilo consistente reforçam sua marca pessoal ou corporativa. Um bom fotógrafo sabe alinhar a imagem com os valores, o tom e o público que você deseja atingir. </p></div><div><h2 class=''subtitle''>5. Versatilidade e adaptação</h2> <p class=''description''> Uma sessão bem planejada gera diversas opções de imagens que podem ser usadas em diferentes formatos: banners, posts, stories, assinaturas de e-mail, folders, entre outros. </p></div><div><h2 class=''subtitle''>6. Economia a longo prazo</h2> <p class=''description''> Embora o investimento inicial pareça alto, uma boa sessão de fotos garante material de qualidade por muito tempo, evitando o uso de imagens improvisadas ou com baixa resolução. </p></div><div><h2 class=''subtitle''>7. Melhora o engajamento nas redes sociais</h2> <p class=''description''> Pessoas se conectam com rostos e histórias reais. Um retrato profissional bem feito humaniza sua presença online e gera mais empatia do público. </p></div></div>
<p class=''description''>Seguem alguns exemplos de posts dos meus clientes e como usaram minhas fotos para divulgação de seus trabalhos, aproveito essa oportunidade para agradecer cada um deles pela oportunidade de fazer parte de suas jornadas empreendedoras, é muito satisfatório ver meu trabalho aplicado em suas redes sociais 🥰</p>', album = '[{"imageId":"fa36d45a-d52f-45be-1707-f2984650fa00","width":468,"height":703,"format":"retrato","customClass":"w33","ratio":"100/122","alt":"","nome":"Dra. Ivana Geraldeli Chediak | Endocrinologia & Metabologia","instagram":"https://www.instagram.com/draivanageraldeli/"},{"imageId":"e7b7f079-b13b-4923-a379-194f0fb72500","width":468,"height":703,"format":"retrato","customClass":"w33","ratio":"100/122","alt":"","nome":"Vert&Con - Consultoria Edge e Aqua | Projetos e Instalação de Drywall","instagram":"https://www.instagram.com/vertconengenharia/"},{"imageId":"0161990a-1590-4c9e-05b6-79cc0595bb00","width":468,"height":703,"format":"retrato","customClass":"w33","ratio":"100/122","alt":"","nome":"RHF Talentos Mogi das Cruzes Centro SP","instagram":"https://www.instagram.com/rhf_mogidascruzescentrosp/"},{"imageId":"2cdb713d-d24d-485a-efc2-61c531065600","width":468,"height":703,"format":"retrato","customClass":"w33","ratio":"100/122","alt":"","nome":"Karoline Siqueira | Estratégia e Marketing","instagram":"https://www.instagram.com/salviacomunicacao/"},{"imageId":"58496c79-1362-47ac-6d3f-d8584bbbfd00","width":468,"height":703,"format":"retrato","customClass":"w33","ratio":"100/122","alt":"","nome":"POLLYANNA GONÇALVES - Psicóloga e Neurocientista","instagram":"https://www.instagram.com/apsipollyanna/"},{"imageId":"de4747f6-9665-4898-a481-3db0164eee00","width":468,"height":703,"format":"retrato","customClass":"w33","ratio":"100/122","alt":"","nome":"Psicóloga Naiara S Amaral","instagram":"https://www.instagram.com/naiaraamaral_psi/"},{"imageId":"e0aaeccd-d6ef-48f9-3f56-19aea1f6ad00","width":703,"height":703,"format":"retrato","customClass":"w33 square","alt":"","nome":"Andresa Maia Psicanalista Espiritualista | Humanoterapeuta","instagram":"https://www.instagram.com/dremaia_terapias/"},{"imageId":"2133251a-c87a-4ed3-d424-17d98ae88500","width":703,"height":703,"format":"retrato","customClass":"w33 square","alt":"","nome":"Nelma Caroline - Fonoaudiologia todo dia","instagram":"https://www.instagram.com/fono_nelmacaroline/"},{"imageId":"cbcdf127-3976-481b-ffa5-352533440300","width":703,"height":703,"format":"retrato","customClass":"w33 square","alt":"","nome":"Camila Nogueira | Arquiteta - Studio CN","instagram":"https://www.instagram.com/studiocnmais/"},{"imageId":"f2ad1126-fa7f-4699-d01b-048b8e482e00","width":703,"height":703,"format":"retrato","customClass":"w33 square","alt":"","nome":"Elisabete Cordeiro Fisioterapeuta e Terapeuta Integrativa","instagram":"https://www.instagram.com/_elisabetecordeiro/"}]' WHERE slug = 'vantagens-fotos-corporativas';
UPDATE blog_posts SET conteudo = '<h2 class=''title''>O presente que ela realmente merece</h2>
<p class=''description''>Todo ano a mesma dúvida: o que dar de presente para a mãe? Flores murcham, perfumes acabam e roupas ficam no fundo do armário. Mas sabe o que nunca perde o valor? <b>Uma lembrança de verdade.</b></p>
<p class=''description''>Um ensaio fotográfico profissional é mais do que simples fotos. É uma experiência que faz sua mãe se sentir especial, valorizada e bonita, do jeito que você sempre a enxerga.</p>
<p class=''description''>E o melhor: diferente de outros presentes, as fotos ficam para sempre. Ela vai lembrar desse momento toda vez que olhar para as imagens na parede da sala, no álbum da estante ou na foto de perfil do WhatsApp.</p>
<h2 class=''title''>Como funciona o presente de ensaio fotográfico</h2>
<p class=''description''>O processo é simples e pensado para ser uma surpresa perfeita:</p>
<p class=''description''><b>1. Você escolhe o pacote</b>, temos opções que cabem em diferentes bolsos, desde o mais acessível até o premium com álbum incluso.</p>
<p class=''description''><b>2. Recebe o kit presente</b>, preparamos um vale-ensaio personalizado que pode vir em uma nécessaire especial ou envelope lacrado. Sua mãe abre no Dia das Mães e descobre a surpresa!</p>
<p class=''description''><b>3. Ela agenda quando quiser</b>, sem pressa. Sua mãe escolhe o melhor dia e horário pelo WhatsApp.</p>
<p class=''description''><b>4. Experiência no estúdio</b>, no dia do ensaio, ela será direcionada em cada pose. Não precisa saber posar: <b>nós cuidamos de tudo</b>.</p>
<p class=''description''><b>5. Fotos entregues editadas</b>, fotos profissionais prontas para compartilhar, imprimir e guardar para toda a vida.</p>
<h2 class=''title''>Por que um ensaio fotográfico em Mogi das Cruzes?</h2>
<p class=''description''>Nosso <a href=''/estudio''>estúdio fotográfico em Mogi das Cruzes</a> fica no centro da cidade, em frente ao estacionamento da prefeitura, fácil de chegar e com ótimo acesso para quem vem de toda a região do Alto Tietê.</p>
<p class=''description''>O espaço foi pensado para proporcionar uma experiência acolhedora: cenários exclusivos, iluminação profissional e todo o conforto para que sua mãe se sinta à vontade.</p>
<p class=''description''>Atendemos famílias de Mogi das Cruzes, Suzano, Itaquaquecetuba, Poá, Ferraz de Vasconcelos, Guararema, Biritiba Mirim e toda a região.</p>
<h2 class=''title''>O que as mães falam sobre o ensaio</h2>
<p class=''description''>"<i>Maravilhosa! Eu já fiz 2x fotos, fiz minha coloração pessoal, e eu amo!</i>", Esse é um dos muitos depoimentos de mães que viveram a experiência no nosso estúdio. Veja mais em nosso <a href=''/depoimentos''>depoimentos de clientes</a>.</p>
<p class=''description''>"<i>A experiência de fotos e análise de coloração pessoal com a Lillia é fantástica.</i>".</p>
<p class=''description''>"Além do ensaio, muitas mães aproveitam para fazer a <a href=''/analise-coloracao-pessoal-em-mogi''>análise de coloração pessoal</a>, descobrindo quais cores valorizam sua beleza natural.</p>
<h2 class=''title''>Veja os pacotes de presente de Dia das Mães</h2>
<p class=''description''>Preparamos pacotes especiais para o Dia das Mães, com opções para diferentes perfis e bolsos. Cada pacote inclui direção de poses, fotos editadas e a experiência completa no estúdio.</p>
<a href=''/presente-ensaio-fotografico-mogi/dia-das-maes'' class=''link-interno''>Conheça os pacotes de ensaio para Dia das Mães em Mogi das Cruzes →</a>
<p class=''description''>Quer conhecer mais opções de presente com ensaio fotográfico? Temos ideias para aniversários, casais e outras datas especiais.</p>
<a href=''/presente-ensaio-fotografico-mogi'' class=''link-interno''>Veja todas as ideias de presente com ensaio fotográfico →</a>
<p class=''description''>E se você quer ver exemplos reais de ensaios de Dia das Mães feitos no nosso estúdio:</p>
<a href=''/ensaio-fotografico/dia-das-maes'' class=''link-interno''>Confira nosso portfólio de Dia das Mães →</a>' WHERE slug = 'presente-dia-das-maes-ensaio-fotografico';

-- Total: 6 posts