-- Auto-generated backfill for portfolio_works.descricao + artigo
-- Apply after migration 004_portfolio_descricao.sql

UPDATE portfolio_works SET descricao='<p></p>', artigo='a' WHERE slug='corporativo/daniela-lima';
UPDATE portfolio_works SET descricao='Um ensaio lindo feito para a Dra. Ivana Geraldelli', artigo='a' WHERE slug='corporativo/ivana-geraldelli';
UPDATE portfolio_works SET descricao='A Dra. Natalia é uma das 3 sócias da Gerevini Lemes Sociedade de Advogadas, sociedade de mulheres na minha visão feminina, adorei viver essa experiência com vocês.<br><b>Instagram:</b> <a href="https://www.instagram.com/gladvogadas_/" target="_blank">Gerevini &amp; Lemes Sociedade de Advogadas</a><br><b>Site:</b>&nbsp;<a href="https://www.gladvogadas.com.br/" target="_blank">www.gladvogadas.com.br</a>', artigo='a' WHERE slug='corporativo/natalia-lemes';
UPDATE portfolio_works SET descricao='<p></p>', artigo='a' WHERE slug='corporativo/etiene-ferraz';
UPDATE portfolio_works SET descricao='<p></p>', artigo='a' WHERE slug='corporativo/monica.rafael';
UPDATE portfolio_works SET descricao='<p></p>', artigo='a' WHERE slug='corporativo/sheila-lima';
UPDATE portfolio_works SET descricao='<p>Posicionamento de imagem realizado pela fotógrafa Lillia Tavares para a <a href="https://beacons.ai/marcellacastelucci" title="Dra Marcella Castelucci" target="_blank" rel="noopener">Advogada Familiarista - Dra Marcella Castelucci</a><br>Apaixonada por famílias felizes e acordos justos.<br>Especialista em divórcio e inventários.</p>', artigo='a' WHERE slug='corporativo/marcella-castelucci';
UPDATE portfolio_works SET descricao='<p></p>', artigo='a' WHERE slug='corporativo/juliana-kozma';
UPDATE portfolio_works SET descricao='<p>Posicionamento de imagem realizado pela fotógrafa Lillia Tavares para a <a href="https://www.instagram.com/geovanapontesadvocacia/" target="_blank" rel="noopener">advogada Geovana Pontes</a> Advocacia especializada - Previdenciário, Cível e Trabalhista - Atendimento on-line e presencial</p>', artigo='a' WHERE slug='corporativo/geovana-pontes';
UPDATE portfolio_works SET descricao='<p></p>', artigo='a' WHERE slug='corporativo/bruna-freire';
UPDATE portfolio_works SET descricao='<p></p>', artigo='o' WHERE slug='corporativo/gustavo-okazaki';
UPDATE portfolio_works SET descricao='<p>Posicionamento de imagem realizado pela fot&oacute;grafa Lillia Tavares para a engenheira civil Vanessa Lima (<a href="https://www.instagram.com/vanessademelo.lima/" title="Vanessa Lima" target="_blank" rel="noopener">@vanessademelo.lima</a>) especializada em Gestão de Projetos pela USP e acessibilidade. O ensaio corporativo feminino foi produzido no (<a href="https://www.fotografalilliatavares.com.br/estudio" title="Estúdio Lillia Tavares" target="_blank" rel="noopener">Estúdio Lillia Tavares</a>).</p>', artigo='a' WHERE slug='corporativo/vanessa-lima';
UPDATE portfolio_works SET descricao='<p>Posicionamento de imagem realizado pela fot&oacute;grafa Lillia Tavares para a linda Karoline Siqueira (<a href="https://www.instagram.com/salviacomunicacao/" title="Salvia Comunica&ccedil;&atilde;o" target="_blank" rel="noopener">@salviacomunicacao</a>) que oferece servi&ccedil;os de <span>estrat&eacute;gia e marketing digital. O ensaio corporativo feminino foi produzido no Estúdio Amorim.</span></p>', artigo='a' WHERE slug='corporativo/karoline-siqueira';
UPDATE portfolio_works SET descricao='<p>Posicionamento de imagem realizado pela fot&oacute;grafa Lillia Tavares para a psicoterapeuta Andresa Maia (<a href="https://www.instagram.com/dremaia_terapias/" title="Andresa Maia" target="_blank" rel="noopener">@dre_terapeuta</a>) - Psicanálise, Terapias energéticas e espirituais. O ensaio corporativo feminino foi produzido no (<a href="https://www.fotografalilliatavares.com.br/estudio" title="Estúdio Lillia Tavares" target="_blank" rel="noopener">Estúdio Lillia Tavares</a>).</p>', artigo='a' WHERE slug='corporativo/andresa-maia';
UPDATE portfolio_works SET descricao='<p>Esse ensaio é muito especial para mim, pois a Camila Nogueira foi a arquiteta responsável pelo nosso estúdio. Em seu perfil no <a href="https://www.instagram.com/studiocnmais" target="_blank">instagram</a> ela traz a frase: <i>"Sua vida através da psicoarquitetura!"</i> e não podia estar mais certa. No meu ambiente de trabalho, me sinto em casa, confortável, ela transforma seus ambientes em espaços acolhedores e inspiradores.</p>', artigo='a' WHERE slug='corporativo/camila-nogueira';
UPDATE portfolio_works SET descricao='<p>Ensaio corporativo pela fot&oacute;grafa Lillia Tavares para a fonoaudióloga Nelma Caroline (<a href="https://www.instagram.com/fono_nelmacaroline/" title="Nelma Caroline" target="_blank" rel="noopener">@fono_nelmacaroline</a>) que trabalha com 🔹 Linguagem infantil: autismo, trocas fonológicas, gagueira, leitura/escrita, seletividade alimentar, 🔹Motricidade orofacial 🔹TPAC. O ensaio corporativo feminino foi produzido no (<a href="https://www.fotografalilliatavares.com.br/estudio" title="Estúdio Lillia Tavares" target="_blank" rel="noopener">Estúdio Lillia Tavares</a>).</p>', artigo='a' WHERE slug='corporativo/nelma-caroline';
UPDATE portfolio_works SET descricao='<p>Quem disse que foto corporativa precisa ser séria e sem charme? Bora mostrar que profissionalismo também pode ter leveza, personalidade e muita autenticidade!<br>O ensaio com a Psicoterapeuta Pollyanna é a prova disso!</p>', artigo='a' WHERE slug='corporativo/pollyanna-goncalves';
UPDATE portfolio_works SET descricao='<p>Ensaio Sensual/intimista realizado pela fot&oacute;grafa Lillia Tavares para a Daniele Sato. Esse ensaio feminino foi produzido na Casa Tereza de Pilar.</p>', artigo='a' WHERE slug='sensual-intimista/daniele-sato';
UPDATE portfolio_works SET descricao='<p></p>', artigo='a' WHERE slug='sensual-intimista/tayna-marcondes';
UPDATE portfolio_works SET descricao='<p></p>', artigo='a' WHERE slug='sensual-intimista/elaine-fernanda';
UPDATE portfolio_works SET descricao='<p>Ensaio Sensual/intimista realizado pela fotógrafa Lillia Tavares para a Vanessa Lima. O ensaio intimista feminino foi produzido no Estúdio de fotografia Lillia Tavares.</p>', artigo='a' WHERE slug='sensual-intimista/vanessa-lima';
UPDATE portfolio_works SET descricao='<p>Ensaio Sensual realizado pela fot&oacute;grafa Lillia Tavares para a linda Cris Borges. O ensaio intimista feminino foi produzido no LV Estúdio.</p>', artigo='a' WHERE slug='sensual-intimista/cris-borges';
UPDATE portfolio_works SET descricao='<p>Ensaio de Pole Sport e Lira realizado pela fot&oacute;grafa Lillia Tavares para a linda Cris. O ensaio intimista feminino foi produzido no (<a href="https://www.instagram.com/studiololaschueler" title="Studio Lola Schueler" target="_blank" rel="noopener">Studio Lola Schueler</a>).</span></p>', artigo='a' WHERE slug='sensual-intimista/cris-pole-e-lira';
UPDATE portfolio_works SET descricao='<p>Um ensaio com 3 lindas gerações, a vovó Rose, a mamãe Vanessa e a netinha Giugiu, elas me deram a alegria de fotografá-las ❤️</p>', artigo='a' WHERE slug='dia-das-maes/rosiney-de-melo';
UPDATE portfolio_works SET descricao='<p>não existe conexão maior que a de mãe e filho, me senti honrada em poder registrar esse amor transbordando, muito obrigado Thainá.</p>', artigo='a' WHERE slug='dia-das-maes/thaina-porto';
UPDATE portfolio_works SET descricao='<p>O dia em que a fotógrafa vira a modelo, fiz esse ensaio para homenagear as mulheres mais fortes e inspiradoras da minha vida, minha avó Maria e minha mãe Sandra, entre em contato e agende um ensaio com sua rainha também ❤️</p>', artigo='a' WHERE slug='dia-das-maes/lillia-tavares';
